# Generated by Django 3.2 on 2021-04-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_about_comment_post'),
    ]

    operations = [
    ]
