# Generated by Django 3.2 on 2021-04-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'get_latest_by': ['title']},
        ),
    ]
