# Generated by Django 3.2 on 2021-04-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myteam',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
