# Generated by Django 3.2 on 2021-04-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
