# Generated by Django 3.2 on 2021-04-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210416_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Service',
        ),
    ]
