# Generated by Django 3.2 on 2021-04-16 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_post_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Post',
        ),
    ]
